# -*- coding: utf-8 -*-
"""Day 6 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTE0XzhRR-2EKyGxFy5RTuiYgCXQ3ogr
"""

list1=["a","b","c","d","e"]
list2=[1,2,3,4,5,6,7,8]
print ("the original key is:" + str(list1))
print ("the original value is:" + str(list2))
res={list1[i]:list2[i] for i in range(len(list1))}
print ("resultant dictionary is :" + str(res))